project_id = "tjgbyygllssqsywxpxqe"

[functions.agent]
verify_jwt = true

[functions.tenderbot]
verify_jwt = true

[functions.rams]
verify_jwt = true

[functions.smartops]
verify_jwt = true

[functions.quote-bot]
verify_jwt = true

[functions.tax-bot]
verify_jwt = true

[functions.tender-search]
verify_jwt = true

[functions.civix-api]
verify_jwt = true

[functions.task-scheduler]
verify_jwt = false

[functions.tenders]
verify_jwt = true

[functions.quotes]
verify_jwt = true

[functions.funding-bot]
verify_jwt = true

[functions.risk-bot]
verify_jwt = true

[functions.bid-package]
verify_jwt = true

[functions.webhook-manager]
verify_jwt = true

[functions.business-analytics]
verify_jwt = true

[functions.project-management]
verify_jwt = true

[functions.welcome-email]
verify_jwt = false
