project_id = "tjgbyygllssqsywxpxqe"

[functions.agent]
verify_jwt = true

[functions.tenderbot]
verify_jwt = true

[functions.rams]
verify_jwt = true

[functions.smartops]
verify_jwt = true

[functions.quote-bot]
verify_jwt = true

[functions.tax-bot]
verify_jwt = true

[functions.tender-search]
verify_jwt = true

[functions.civix-api]
verify_jwt = true

[functions.task-scheduler]
verify_jwt = false

[functions.tenders]
verify_jwt = false
