name = "bill-master-flex"
compatibility_date = "2024-08-19"

[env.production]
# Build configuration for Cloudflare Pages
# Build command: npm run build
# Build output directory: dist
# Root directory: .

# Environment variables can be set in Cloudflare dashboard
# NODE_VERSION = "20"